drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan24
        when 
            p: OrderRequest(age >= 24)
        then
            System.out.println(p.getCustomerType() + " is 24 or over.");
    end
