drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan3
        when 
            p: OrderRequest(age >= 3)
        then
            System.out.println(p.getCustomerType() + "is 3 or over.");
    end
