drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan20
        when 
            p: OrderRequest(age >= 20)
        then
            System.out.println(p.getCustomerType() + " is 20 or over.");
    end
