drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan25
        when 
            p: OrderRequest(age >= 25)
        then
            System.out.println(p.getCustomerType() + " is 25 or over.");
    end
