drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan5
        when 
            p: OrderRequest(age >= 5)
        then
            System.out.println(p.getName() + "is 5 or over.");
    end
