drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan18
        when 
            p: OrderRequest(age >= 18)
        then
            System.out.println(p.getCustomerType() + "is 18 or over.");
    end
