drools:
  orderRules: >
    
    import com.olx.model.OrderRequest;
    
    rule isAgeGeaterThan30
        when 
            p: OrderRequest(age >= 30)
        then
            System.out.println(p.getCustomerType() + " is 30 or over.");
    end
