drools:
  orderRules: >
    import com.olx.model.OrderRequest;
    
    import com.olx.model.CustomerType;
    
    import com.olx.model.OrderDiscount;
    
    
    rule 'Age based discount'
        when
            OrderRequest(age < 20 || age > 50)
        then
            orderDiscount.setDiscount(orderDiscount.getDiscount() + 10);
    end
